#pragma once

#define LIB_UTILS_LOG

//#define LIB_MODULE_CAMERA_VC0706_CONFIG
//#define LIB_MODULE_CAMERA_VC0706_AUTOBAUDING_SHORT
//#define LIB_MODULE_CAMERA_VC0706_SERIAL_PORT_SET_BAUDRATE
//#define LIB_MODULE_CAMERA_VC0706_INITIALIZE_CONFIG
//#define LIB_MODULE_CAMERA_VC0706_CHECK_CONNECT_TIME         1//s
//#define LIB_MODULE_CAMERA_VC0706_CHECK_CONNECT_FAIL_TIME    LIB_MODULE_CAMERA_VC0706_CHECK_CONNECT_TIME + 3//s
